// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrAsNr6DGsguUCbs0djPuLxCkP1mKY6cs',
    appId: '1:241480766012:web:c88adeb0c2e206443a6939',
    messagingSenderId: '241480766012',
    projectId: 'fitnessmobile-bf260',
    authDomain: 'fitnessmobile-bf260.firebaseapp.com',
    storageBucket: 'fitnessmobile-bf260.firebasestorage.app',
    measurementId: 'G-9531QYF6ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCLAdrJi5JIczoumnqwDyCiOpMUxKdIQE',
    appId: '1:241480766012:android:f7dd4e91dad701f03a6939',
    messagingSenderId: '241480766012',
    projectId: 'fitnessmobile-bf260',
    storageBucket: 'fitnessmobile-bf260.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP2-SrLzgUUgc1q52SwYj9zHi695YhoOE',
    appId: '1:241480766012:ios:9f0cc44b9e322d913a6939',
    messagingSenderId: '241480766012',
    projectId: 'fitnessmobile-bf260',
    storageBucket: 'fitnessmobile-bf260.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP2-SrLzgUUgc1q52SwYj9zHi695YhoOE',
    appId: '1:241480766012:ios:9f0cc44b9e322d913a6939',
    messagingSenderId: '241480766012',
    projectId: 'fitnessmobile-bf260',
    storageBucket: 'fitnessmobile-bf260.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrAsNr6DGsguUCbs0djPuLxCkP1mKY6cs',
    appId: '1:241480766012:web:cc0d39966910492e3a6939',
    messagingSenderId: '241480766012',
    projectId: 'fitnessmobile-bf260',
    authDomain: 'fitnessmobile-bf260.firebaseapp.com',
    storageBucket: 'fitnessmobile-bf260.firebasestorage.app',
    measurementId: 'G-KX4XMKZBWZ',
  );
}
