name: fitnessapp
description: "A new Flutter project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase packages
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_ui_auth: ^1.16.0
  firebase_ui_oauth_google: ^1.4.0
  google_sign_in: ^6.2.2
  firebase_storage: ^12.4.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  # Updated from 0.18.0 to 0.19.0
  shared_preferences: ^2.3.5
  universal_html: ^2.2.4
  syncfusion_flutter_charts: ^29.2.11
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  fl_chart: ^0.65.0
  simple_animation_progress_bar: ^1.6.0
  dotted_dashed_line: ^0.0.3
  simple_circular_progress_bar: ^1.0.2
  animated_toggle_switch: ^0.6.2
  flutter_native_splash: ^2.3.1
  readmore: ^2.1.0
  google_generative_ai: ^0.4.7  # Update to the latest version
  cloud_firestore: ^5.6.1
  cached_network_image: ^3.4.1
  dart_openai: ^4.0.0  # Add this
  connectivity_plus: ^4.0.2
  permission_handler: ^10.2.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#010101"
  image: assets/images/app_logo.png
  android_12:
    color: "#ffffff"
    color_dark: "#010101"
    image: assets/images/app_logo.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1  # Ensure this is the latest version
  flutter_application_1: ^0.0.2

flutter:
  uses-material-design: true
  
  assets:
     - assets/icons/
     - assets/images/
     - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo_foreground.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo_foreground.png"
